### ISSUE TITLE
Error: Unable to load valid system manifest

### ISSUE THREAD

**Issue by elmorte1** [fvtt-fria-ligan/deathinspace-foundry-vtt#33]
When installing in current version of foundry vtt it gives the error:
{"level":"error","message":"Metadata validation failed for system \"deathinspace\": System validation errors:\n  packs: \n    16: \n      type: may not be undefined\n    15: \n      type: may not be undefined\n    14: \n      type: may not be undefined\n    13: \n      type: may not be undefined\n    12: \n      type: may not be undefined\n    11: \n      type: may not be undefined\n    10: \n      type: may not be undefined\n    9: \n      type: may not be undefined\n    8: \n      type: may not be undefined\n    7: \n      type: may not be undefined\n    6: \n      type: may not be undefined\n    5: \n      type: may not be undefined\n    4: \n      type: may not be undefined\n    3: \n      type: may not be undefined\n    2: \n      type: may not be undefined\n    1: \n      type: may not be undefined\n    0: \n      type: may not be undefined","stack":"Error: Metadata validation failed for system \"deathinspace\": System validation errors:\n  packs: \n    16: \n      type: may not be undefined\n    15: \n      type: may not be undefined\n    14: \n      type: may not be undefined\n    13: \n      type: may not be undefined\n    12: \n      type: may not be undefined\n    11: \n      type: may not be undefined\n    10: \n      type: may not be undefined\n    9: \n      type: may not be undefined\n    8: \n      type: may not be undefined\n    7: \n      type: may not be undefined\n    6: \n      type: may not be undefined\n    5: \n      type: may not be undefined\n    4: \n      type: may not be undefined\n    3: \n      type: may not be undefined\n    2: \n      type: may not be undefined\n    1: \n      type: may not be undefined\n    0: \n      type: may not be undefined\n    at DataModelValidationFailure.asError (file:///home/foundry/resources/app/common/data/validation-failure.mjs:81:12)\n    at System.validate (file:///home/foundry/resources/app/common/abstract/data.mjs:308:59)\n    at System.validate (file:///home/foundry/resources/app/dist/packages/system.mjs:1:645)\n    at new DataModel (file:///home/foundry/resources/app/common/abstract/data.mjs:62:10)\n    at new BasePackage (file:///home/foundry/resources/app/common/packages/base-package.mjs:108:5)\n    at new BaseSystem (file:///home/foundry/resources/app/common/packages/base-system.mjs:15:16)\n    at new ServerPackageMixin (file:///home/foundry/resources/app/dist/packages/package.mjs:1:2074)\n    at new System (file:///home/foundry/resources/app/dist/packages/system.mjs:1:348)\n    at System.fromManifestPath (file:///home/foundry/resources/app/dist/packages/package.mjs:1:6226)\n    at file:///home/foundry/resources/app/dist/packages/package.mjs:1:5357","timestamp":"2023-05-29 18:53:55"}

**Comment by asherett** [comment]
Probably fixed by 4.0.0 (at least not a problem here), can probably be closed?
